apiVersion: v1
kind: Namespace
metadata:
  name: webhook-system
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-tls
  namespace: webhook-system
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoakNDQW02Z0F3SUJBZ0lKQU1ybEVSeE04aHN0TUEwR0NTcUdTSWIzRFFFQkN3VUFNQlV4RXpBUkJnTlYKQkFNTUNuZGxZbWh2YjJzdFkyRXdIaGNOTWpVeE1UQTVNVEV3TWpBeFdoY05NelV4TVRBM01URXdNakF4V2pBcwpNU293S0FZRFZRUUREQ0Z3YjJRdGJYVjBZWFJsTFhOMll5NTNaV0pvYjI5ckxYTjVjM1JsYlM1emRtTXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGMyUzJrdlRxYVJGcHMvWk03MktRK0poWk8KdlpodkczVXEwdnFwN2MrQ2g2V0JCUStsNmt5Q0thampwZE43SCtmQUtraGNFY1YraUFWSysvUG5zdFM0d1phWAp6aDRwNmRJSG5lSkZyUVBDOE1HUjkraVdkRzZQZGltc2Z3SlM3WDJjMG1wR0pZb1g3ZCtqOFpua3VWVjhGWmZnClpOYUlJdWVWNVR1QkVsNE5ETHBacExPUWtHaW94d2xFSnpneUZNZzdWRWl4UlpIQU9MM2xLblhvd2t5VW9rcTYKTEdCREkvOHlHbnZ5bXJqeFI5WHJ4SUNoS1F4QWVKcGtjbnM5YzhZVUxkNVRUdGpBeTk4bUVMa0ZYY0VLYVZaeAovR2xsTnFJaU93ZTZ1Uzh4SGJWV0c0L2N3dHZIemFrVFlrekxpTGl2Y3k1V3h1V2xsMy9kR3Z2SjV3ZEhBZ01CCkFBR2pnY0V3Z2I0d0NRWURWUjBUQkFJd0FEQUxCZ05WSFE4RUJBTUNCZUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUIKQlFVSEF3RXdnWTRHQTFVZEVRU0JoakNCZzRJT2NHOWtMVzExZEdGMFpTMXpkbU9DSFhCdlpDMXRkWFJoZEdVdApjM1pqTG5kbFltaHZiMnN0YzNsemRHVnRnaUZ3YjJRdGJYVjBZWFJsTFhOMll5NTNaV0pvYjI5ckxYTjVjM1JsCmJTNXpkbU9DTDNCdlpDMXRkWFJoZEdVdGMzWmpMbmRsWW1odmIyc3RjM2x6ZEdWdExuTjJZeTVqYkhWemRHVnkKTG14dlkyRnNNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFSUWZHOGc5NCttTHc2YkJCOS8rZVhna1piRHQ2VwpOL3htUlArTzNDNTFLL2x6ZnQ5cjdLYUxUbVpIWXRlK0xyTnZnTDA1T2Vsd21ZQWNTWXpjTXdXRGp5aXN5S3BRClFEbXVIRjh0TFNTNGpQVExoTmd3RWE0Z0tobzlUODV6dEorV3VXRCtkMUhIMXJES3l3Ty9XTGZ0Y2Z4T2tld3QKNnJ6aGYzbmtLbHpOL0gzYVQyemtlbWtOWGRiOUFoTk1QTSszS3c2YkxRbCt4OVdBTHdsNDc4UUdleklPelJkcgpkc3BoRldJTmVHVEJ1ai9uWnZhVVNRY3ZEMlB6N0ppQVc5OUNXd2NLMzVDWkNVUHpZRFhyYkR3K1BjM1d2ZS9zCnJLQk1zZ2U1WU1wWHRhcDdIK0NmUDY1MTBPWENIUW54ZEY2SUorRmY4aUNGaHpLL2Z6b0ZvRVpSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBM05rdHBMMDZta1JhYlAyVE85aWtQaVlXVHIyWWJ4dDFLdEw2cWUzUGdvZWxnUVVQCnBlcE1naW1vNDZYVGV4L253Q3BJWEJIRmZvZ0ZTdnZ6NTdMVXVNR1dsODRlS2VuU0I1M2lSYTBEd3ZEQmtmZm8KbG5SdWozWXBySDhDVXUxOW5OSnFSaVdLRiszZm8vR1o1TGxWZkJXWDRHVFdpQ0xubGVVN2dSSmVEUXk2V2FTegprSkJvcU1jSlJDYzRNaFRJTzFSSXNVV1J3RGk5NVNwMTZNSk1sS0pLdWl4Z1F5UC9NaHA3OHBxNDhVZlY2OFNBCm9Ta01RSGlhWkhKN1BYUEdGQzNlVTA3WXdNdmZKaEM1QlYzQkNtbFdjZnhwWlRhaUlqc0h1cmt2TVIyMVZodVAKM01MYng4MnBFMkpNeTRpNHIzTXVWc2JscFpkLzNScjd5ZWNIUndJREFRQUJBb0lCQVFDYnBVUVIwbnMydGUyMAoycEdsbisxQkQ3NnhCOVlpbUF0ZmZ3bkNNU1FLTG1kcUlwTUFyN3YwRUVCREVGK1hhc2orR2M2ZGRMam5rQjJLCjF6N3lrSXB6RzV4eXFJV0JySlNsWVpSUzNyakQ3c0c5aWlhVndzRVl3b0prVzY3Ym14em9KVE5ZOUtQNmNWOG8KUCtIaDNPeHVZeG1Dd0E2aUsxZGp3UWJLMUpNTVJoZ2N2cmNEV2g0YjJyb1E0S1ZKelBQaWtTdkdpVm02dnlwYwp6V2NJb3lQMEVOUjVKbE9JWUsrMGM0M2kyTDMxTE9taURvSXVnMlVSTUFyWnBmZ25vYmEzMGovUk9qa0tBMEViCk8wY3Fsdm9ZWnRZVXhLY2tnMXFpWnBJOExNaVdOd282ZHpDK0JLZWFoVUpiWkRIa0FVenFOM2dTK2pVMG5PQ0cKTkUxdm14bEJBb0dCQVA5aDZlL1VWQlBxL2ZGWlFrd3VXK0Vmd2pCblFTYTNDeG45Wm5oVmJpTHdvZ2l3MDVKTQpKOUp6cmNBR1dqeGZRNkIvSUxldlBiK2EycWdWRHFsSUhIZ2VnSGpFbG56NjhiMFdYbnU1L3hvNE9iWml3aUNDCjRueGxPN3dqV1ovRTBSaGtGL04zR0kxU0RvUERNd0ZkOW1pVmY0UmtBRnQ1WVd5dmFFaWRabDBQQW9HQkFOMWgKNHlOU2J0T251TEx2S0haMFNsbzlrdkpRSnZVNCtPOTJOZmYvM01BWHFLNjBRNXNpdEI3NFJXUWRoWlk3b0F6UQpiV1prZkg2bzZnamV2UUJKQzZzekJGOWxwa2IwSkZlQUFqZG9zR2xwc1VOZUtTdDFLN0VBaXhqd2I4amZLbHVJCjVhUWd1dXpaVHZ0R1dXT01VMy9iMmN6MnV6dGRMSDIyTWgxSC9hSkpBb0dCQU5WUUhzd1JhWTBkaXJHT1lkOHEKRmRxcjRWTDIzQ2VQV3ZtQmZKYmtuTk1ZZGUrV2E1SldoQ2k0TVJnazlqaFpSaTZJSVhic0xFS2dBU1hHT1BIUwo1dHk2ZFlycWdkeXc2enlLczY3YkJDY05jYjlUTEYxbGxmSmJ5SkowWUljZ0tac2ErQnFIanYxejNlWFhKUUp1ClRzUzZvc0dkbWVMT056OUdJSEFPOFJLbkFvR0JBTm9kcWFhUmZ6UDEyZG9pRytHcGJlQS9MbHFqY2Q3RnhTNVoKYjQ3cWZscWNkTXU4TzZmTHAxK2tDT284MC9OU3g3d1lWdEU5VEJPVzVRN2NOYWJrVVNUWjNRTUlxYXphdWp1agptWXR5RCsyci9zUjdMMkRyenFKVUFMZ1BuSE55dk03MnNCcm5USVF6RHNndlpiN1k4U1BXUGw3YzhWZnAwdjRBCjFwdFc1S1JSQW9HQkFLUTdzOGZlLzlIY3JYR3JhR3BINXdrSWVKWjYzMDZlaEVsRVpvV1RVOVZjV3VlRCtsblcKUi9LMlh3eFVJY3FoY25CdUpxRnFJd1Q1Qk10NXZibThRbWVOWVBMNlFmd29jZzBnWnJWUEdBNWZlQkN3aDJ3eAp4Unk0eGNhQ0RYRmxDVmxWcmlZb01TYWhHbXUreXRaaVBXN0hKQm43VWp0enBUbzBUaElwQzlWMgotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-mutate-webhook
  namespace: webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutate-webhook
  template:
    metadata:
      labels:
        app: mutate-webhook
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: webhook
          image: mutate-webhook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-tls
              mountPath: "/tls"
              readOnly: true
      volumes:
        - name: webhook-tls
          secret:
            secretName: webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pod-mutate-svc
  namespace: webhook-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutate-webhook
